In [1]:
import pandas as pd
import numpy as np

from glob import glob
from tqdm import tqdm

In [2]:
sido_abbr_nm = {
    '서울' : '서울특별시',
    '부산' : '부산광역시',
    '대구' : '대구광역시',
    '인천' : '인천광역시',
    '광주' : '광주광역시',
    '대전' : '대전광역시',
    '울산' : '울산광역시',
    '세종' : '세종특별자치시',
    '경기' : '경기도',
    '강원' : '강원도',
    '충북' : '충청북도',
    '충남' : '충청남도',
    '전북' : '전라북도',
    '전남' : '전라남도',
    '경북' : '경상북도',
    '경남' : '경상남도',
    '제주' : '제주특별자치도',
    '제주도' : '제주특별자치도'
}

# 시군구 지명 바꾸기
def city_sgg_change(sido,sgg):
    if (sido =='인천광역시')&(sgg=='남구'):
        sgg='미추홀구'
    elif (sido =='경기도')&(sgg=='여주군'):
        sgg ='여주시'
    elif (sido =='충청북도')&(sgg=='청원군'):
        sgg ='충주시'
    elif (sido =='세종특별자치시')&(sgg!=sgg):
        sgg ='세종특별자치시'
    elif (sido =='세종특별자치시')&(sgg=='세종시'):
        sgg ='세종특별자치시'
    elif (sido =='세종특별자치시')&(sgg=='연기군'):
        sgg ='세종특별자치시'
     
    return sgg.split(' ')[0] #경기도 구 단위를 시단위로 올리기 위해

## 대상 시군구

In [3]:
import geopandas as gpd

sgg_gdf = gpd.gpd.GeoDataFrame.from_file('../../data/0/shp/sgg.shp', encoding='UTF-8', crs="epsg:4326")
sgg_gdf = sgg_gdf.astype({'SGG_AD_CD':str,'SGG_LE_CD':str})

sgg_df = sgg_gdf[['SGG_AD_CD','SIDO','SGG']].copy()
sgg_df = sgg_df.rename(columns={'SGG_AD_CD':'시군구코드','SIDO':'시도','SGG':'시군구'})

sgg_df

     시군구코드       시도   시군구
0    11010    서울특별시   종로구
1    11020    서울특별시    중구
2    11030    서울특별시   용산구
3    11040    서울특별시   성동구
4    11050    서울특별시   광진구
..     ...      ...   ...
224  38380     경상남도   함양군
225  38390     경상남도   거창군
226  38400     경상남도   합천군
227  39010  제주특별자치도   제주시
228  39020  제주특별자치도  서귀포시

[229 rows x 3 columns]

## 도서관 데이터

In [4]:
lib_df_list =[]

for year in tqdm(range(2014,2019)):
    lib_df=pd.read_excel('../../data/3/pl_statics/'+str(year)+'.xlsx')
    lib_df['시점'] = year
    lib_df_list.append(lib_df)
    
lib_dfs = pd.concat(lib_df_list)
## 국공립 공공도서관 가져오기
lib_dfs = lib_dfs[(lib_dfs['설립주체']!='사립')].reset_index().drop(columns=['index','순번','연번'])

lib_dfs['지역'] = lib_dfs['지역'].apply(lambda x: sido_abbr_nm[x] if x in sido_abbr_nm else x)
lib_dfs['지역_시군구'] = lib_dfs.apply(lambda x:(city_sgg_change(x['지역'],x['지역_시군구'])), axis=1)

lib_dfs = lib_dfs.rename(columns={'지역':'시도','지역_시군구':'시군구'})

lib_dfs

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:22<00:00,  4.49s/it]

,구분,시도,시군구,설립주체,설립주체_기관명,운영방식,운영기관명,분관내용,개관년도,도서관명,...,우편번호,개관시간,휴관일,도서관구성,상위본관명,분류체계,목록규칙_국내서,목록규칙_국외서,저자기호_국내서,저자기호_국외서
0,공공(일반),강원도,영월군,교육청,영월교육지원청,직영,강원도교육청,NaN,1974,영월교육도서관 (구 영월도서관),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,공공(일반),강원도,정선군,교육청,강원도교육청,직영,강원도교육청,NaN,1989,정선교육도서관 (구 정선도서관),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,공공(일반),강원도,동해시,교육청,강원도교육청,직영,강원도교육청,NaN,1988,동해교육도서관 (구 동해도서관),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,공공(일반),강원도,속초시,교육청,강원도교육청,직영,강원도교육청,NaN,1987,속초교육문화관 (구 속초평생교육정보관),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,공공(일반),강원도,홍천군,교육청,강원도교육청,직영,강원도교육청,NaN,1970,홍천교육도서관 (구 홍천도서관),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4947,공공(일반),서울특별시,은평구,지자체,은평구청,위탁,사단법인 더불어배움,NaN,2018,내를건너서숲으로도서관,...,3443.0,NaN,NaN,본관,NaN,NaN,NaN,NaN,NaN,NaN
4948,공공(일반),서울특별시,노원구,지자체,NaN,직영,NaN,NaN,2018,한내지혜의 숲 도서관,...,1912.0,월~금 9:00~18:00 / 토 9:00~17:00,"매주 일요일, 법정공휴일, 임시공휴일",본관,NaN,NaN,NaN,NaN,NaN,NaN
4949,공공(일반),서울특별시,노원구,지자체,노원구청,직영,NaN,NaN,2018,향기나무도서관,...,1786.0,NaN,NaN,본관,NaN,NaN,NaN,NaN,NaN,NaN
4950,공공(일반),서울특별시,중랑구,지자체,중랑구청,위탁,중랑구시설관리공단,NaN,2018,양원숲속도서관,...,2062.0,"평일 09:00~18:00 / 토 09:00 ~17:00, 일 10:00 ~ 17:00","매주 휴관일, 일요일은 제외한 법정공휴일",본관,NaN,KDC,KCR6,NaN,장일세,NaN
4951,공공(일반),서울특별시,종로구,지자체,종로구청,직영,NaN,NaN,2018,어린이청소년국학도서관,...,3070.0,NaN,NaN,본관,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
lib_dfs_sgg = pd.merge(sgg_df, lib_dfs, on=['시도','시군구'],  how='inner')
lib_dfs_sgg

,시군구코드,시도,시군구,구분,설립주체,설립주체_기관명,운영방식,운영기관명,분관내용,개관년도,...,우편번호,개관시간,휴관일,도서관구성,상위본관명,분류체계,목록규칙_국내서,목록규칙_국외서,저자기호_국내서,저자기호_국외서
0,11010,서울특별시,종로구,공공(일반),교육청,서울특별시교육청,직영,서울시교육청,NaN,1920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010,서울특별시,종로구,공공(일반),교육청,서울시교육청,직영,서울시교육청,NaN,1977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010,서울특별시,종로구,공공(일반),지자체(시.도),서울특별시 종로구청,위탁,재단법인 종로문화재단,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010,서울특별시,종로구,공공(일반),지자체(시.도),종로구청,위탁,재단법인종로문화재단,NaN,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010,서울특별시,종로구,공공(어린이),교육청,서울특별시교육청,직영,서울특별시교육청,NaN,1979,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4947,39020,제주특별자치도,서귀포시,공공(일반),지자체,서귀포시,직영,NaN,NaN,2006,...,63544.0,"자료실(09:00~22:00),열람실(08:00~24:00)","매주 월요일, 설날연휴, 추석연휴,1월1일,12월31일",본관,NaN,KDC,KORMARC,KORMARC,이재철저자기호,Cutter-Sanborn Table
4948,39020,제주특별자치도,서귀포시,공공(일반),지자체,서귀포시,직영,NaN,NaN,1998,...,63640.0,08:00~22:00,"매주 금요일, 1월1일, 12월31일, 설연휴, 추석연휴",본관,NaN,KDC,KCR4,NaN,이재철2표,커터샌본
4949,39020,제주특별자치도,서귀포시,공공(일반),지자체,서귀포시,직영,서귀포시,NaN,2001,...,699923.0,08:00~22:00,"1월1일, 설연휴, 추석연휴, 12월31일, 매주 금요일",본관,NaN,KDC5판,KCR3판,KCR3판,이재철2표,이재철2표
4950,39020,제주특별자치도,서귀포시,공공(일반),지자체,서귀포시,직영,서귀포시,NaN,2002,...,699914.0,08:00~22:00,"매주금요일,설,추석연휴,12.31,1.1",본관,NaN,한국십진분류법,KCR4,NaN,이재철 저자기호표(제2표),NaN
4951,39020,제주특별자치도,서귀포시,공공(어린이),지자체,NaN,직영,서귀포시,NaN,2004,...,697837.0,08시~19시,매주 월요일,본관,NaN,KDC,KORMAC,NaN,이재철2,NaN

In [83]:
## 도서관 년식
lib_dfs_sgg['AGE'] = lib_dfs_sgg['시점'] - lib_dfs_sgg['개관년도'] + 1

## 소장 도서
lib_dfs_sgg['도서_총류'] = lib_dfs_sgg[['도서_국내_총류','도서_국외_총류']].sum(axis=1)
lib_dfs_sgg['도서_철학'] = lib_dfs_sgg[['도서_국내_철학','도서_국외_철학']].sum(axis=1)
lib_dfs_sgg['도서_종교'] = lib_dfs_sgg[['도서_국내_종교','도서_국외_종교']].sum(axis=1)
lib_dfs_sgg['도서_사회과학'] = lib_dfs_sgg[['도서_국내_사회과학','도서_국외_사회과학']].sum(axis=1)
lib_dfs_sgg['도서_순수과학'] = lib_dfs_sgg[['도서_국내_순수과학','도서_국외_순수과학']].sum(axis=1)
lib_dfs_sgg['도서_기술과학'] = lib_dfs_sgg[['도서_국내_기술과학','도서_국외_기술과학']].sum(axis=1)
lib_dfs_sgg['도서_예술'] = lib_dfs_sgg[['도서_국내_예술','도서_국외_예술']].sum(axis=1)
lib_dfs_sgg['도서_언어'] = lib_dfs_sgg[['도서_국내_언어','도서_국외_언어']].sum(axis=1)
lib_dfs_sgg['도서_문학'] = lib_dfs_sgg[['도서_국내_문학','도서_국외_문학']].sum(axis=1)
lib_dfs_sgg['도서_역사'] = lib_dfs_sgg[['도서_국내_역사','도서_국외_역사']].sum(axis=1)

lib_dfs_sgg['도서_국내'] = lib_dfs_sgg[['도서_국내_총류','도서_국내_철학','도서_국내_종교', '도서_국내_사회과학', '도서_국내_순수과학', '도서_국내_기술과학', '도서_국내_예술', '도서_국내_언어', '도서_국내_문학','도서_국내_역사']].sum(axis=1)
lib_dfs_sgg['도서_국외'] = lib_dfs_sgg[['도서_국외_총류','도서_국외_철학','도서_국외_종교', '도서_국외_사회과학', '도서_국외_순수과학', '도서_국외_기술과학', '도서_국외_예술', '도서_국외_언어', '도서_국외_문학','도서_국외_역사']].sum(axis=1)

lib_dfs_sgg['도서'] = lib_dfs_sgg[['도서_국내','도서_국외']].sum(axis=1)

## 대출권수 
lib_dfs_sgg['대출권수_총류'] = lib_dfs_sgg[['대출권수_어린이_총류','대출권수_청소년_총류', '대출권수_성인_총류']].sum(axis=1)
lib_dfs_sgg['대출권수_철학'] = lib_dfs_sgg[['대출권수_어린이_철학','대출권수_청소년_철학', '대출권수_성인_철학']].sum(axis=1)
lib_dfs_sgg['대출권수_종교'] = lib_dfs_sgg[['대출권수_어린이_종교','대출권수_청소년_종교', '대출권수_성인_종교']].sum(axis=1)
lib_dfs_sgg['대출권수_사회과학'] = lib_dfs_sgg[['대출권수_어린이_사회과학','대출권수_청소년_종교', '대출권수_성인_종교']].sum(axis=1)
lib_dfs_sgg['대출권수_순수과학'] = lib_dfs_sgg[['대출권수_어린이_순수과학','대출권수_청소년_순수과학', '대출권수_성인_순수과학']].sum(axis=1)
lib_dfs_sgg['대출권수_기술과학'] = lib_dfs_sgg[['대출권수_어린이_기술과학','대출권수_청소년_기술과학', '대출권수_성인_기술과학']].sum(axis=1)
lib_dfs_sgg['대출권수_예술'] = lib_dfs_sgg[['대출권수_어린이_예술','대출권수_청소년_예술', '대출권수_성인_예술']].sum(axis=1)
lib_dfs_sgg['대출권수_언어'] = lib_dfs_sgg[['대출권수_어린이_언어','대출권수_청소년_언어', '대출권수_성인_언어']].sum(axis=1)
lib_dfs_sgg['대출권수_문학'] = lib_dfs_sgg[['대출권수_어린이_문학','대출권수_청소년_문학', '대출권수_성인_문학']].sum(axis=1)
lib_dfs_sgg['대출권수_역사'] = lib_dfs_sgg[['대출권수_어린이_역사','대출권수_청소년_역사', '대출권수_성인_역사']].sum(axis=1)

lib_dfs_sgg['대출권수'] = lib_dfs_sgg[['대출권수_총류','대출권수_철학', '대출권수_종교', '대출권수_사회과학', '대출권수_순수과학', '대출권수_기술과학', '대출권수_예술', '대출권수_문학', '대출권수_역사']].sum(axis=1)

## 정규직 직원수
lib_dfs_sgg['직원_정규직'] = lib_dfs_sgg[['직원_정규직_사서남','직원_정규직_사서여','직원_정규직_행정남','직원_정규직_행정여','직원_정규직_전산남','직원_정규직_전산여', '직원_정규직_기타남', '직원_정규직_기타여']].sum(axis=1)

lib_dfs_sgg.head()

,시군구코드,시도,시군구,구분,설립주체,설립주체_기관명,운영방식,운영기관명,분관내용,개관년도,...,대출권수_종교,대출권수_사회과학,대출권수_순수과학,대출권수_기술과학,대출권수_예술,대출권수_언어,대출권수_문학,대출권수_역사,대출권수,직원_정규직
0,11010,서울특별시,종로구,공공(일반),교육청,서울특별시교육청,직영,서울시교육청,NaN,1920,...,9895.0,9928.0,10113.0,30194.0,29405.0,10043.0,110861.0,23622.0,264927.0,26
1,11010,서울특별시,종로구,공공(일반),교육청,서울시교육청,직영,서울시교육청,NaN,1977,...,9351.0,17783.0,20475.0,26201.0,41553.0,13926.0,130474.0,32511.0,313421.0,60
2,11010,서울특별시,종로구,공공(일반),지자체(시.도),서울특별시 종로구청,위탁,재단법인 종로문화재단,NaN,2014,...,0.0,7.0,23.0,5.0,2.0,0.0,3416.0,16.0,3470.0,5
3,11010,서울특별시,종로구,공공(일반),지자체(시.도),종로구청,위탁,재단법인종로문화재단,NaN,2014,...,146.0,854.0,1643.0,384.0,1271.0,190.0,3041.0,895.0,8813.0,3
4,11010,서울특별시,종로구,공공(어린이),교육청,서울특별시교육청,직영,서울특별시교육청,NaN,1979,...,9096.0,38998.0,97241.0,11966.0,8747.0,36756.0,277921.0,87503.0,568229.0,26

In [84]:
agg_dict = {
    '도서관명':'count',
    '시설_연면적' : 'mean', 
    '시설_연면적' : 'mean', 
    '개관일수': 'mean',
    'AGE': 'mean',
    '직원_정규직' :'sum',
    '도서관총예산' : 'sum',
    '도서_총류' :'sum',
    '도서_철학' :'sum', 
    '도서_종교' :'sum',
    '도서_사회과학' :'sum',
    '도서_순수과학' :'sum',
    '도서_기술과학' :'sum',
    '도서_예술' :'sum', 
    '도서_언어': 'sum',
    '도서_문학' :'sum',
    '도서_역사':'sum', 
    '도서_국내':'sum',
    '도서_국외':'sum',
    '도서':'sum',
    '대출권수_총류':'sum', 
    '대출권수_철학':'sum',
    '대출권수_종교':'sum',
    '대출권수_사회과학':'sum',
    '대출권수_순수과학':'sum',
    '대출권수_기술과학':'sum',
    '대출권수_예술':'sum',
    '대출권수_언어':'sum',
    '대출권수_문학':'sum',
    '대출권수_역사':'sum',
    '대출권수':'sum',   
}

lib_ele_dfs = lib_dfs_sgg[list(agg_dict.keys())]

lib_dfs_sgg = lib_dfs_sgg.groupby(['시군구코드','시도','시군구', '시점']).agg(agg_dict)
lib_dfs_sgg = lib_dfs_sgg.rename(columns={'도서관명':'도서관수'})
lib_dfs_sgg = lib_dfs_sgg.reset_index()
lib_dfs_sgg

,시군구코드,시도,시군구,시점,도서관수,시설_연면적,개관일수,AGE,직원_정규직,도서관총예산,...,대출권수_철학,대출권수_종교,대출권수_사회과학,대출권수_순수과학,대출권수_기술과학,대출권수_예술,대출권수_언어,대출권수_문학,대출권수_역사,대출권수
0,11010,서울특별시,종로구,2014,5,4365.080000,248.200000,34.200000,120,4056263,...,57775.0,28488.0,67570.0,129495.0,68750.0,80978.0,60915.0,525713.0,144547.0,1158860.0
1,11010,서울특별시,종로구,2015,5,4365.080000,313.400000,35.200000,109,8881945,...,65215.0,28633.0,61886.0,139793.0,74229.0,60600.0,63395.0,530515.0,153926.0,1178445.0
2,11010,서울특별시,종로구,2016,5,4365.080000,314.200000,36.200000,110,9549839,...,52432.0,24081.0,51025.0,147009.0,59679.0,65560.0,60013.0,514192.0,139848.0,1100499.0
3,11010,서울특별시,종로구,2017,5,4365.680000,312.200000,37.200000,109,10523986,...,46321.0,18342.0,44181.0,122551.0,53073.0,41027.0,63312.0,489197.0,118147.0,976691.0
4,11010,서울특별시,종로구,2018,6,3721.578333,265.166667,32.000000,111,11319940,...,41833.0,17611.0,43019.0,118400.0,50369.0,36674.0,60670.0,462117.0,113096.0,926578.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,39020,제주특별자치도,서귀포시,2014,11,1841.270000,300.545455,20.363636,60,4595559,...,16010.0,6737.0,16120.0,33091.0,26442.0,17250.0,22014.0,193688.0,38796.0,359513.0
1141,39020,제주특별자치도,서귀포시,2015,11,1841.270000,303.545455,21.363636,67,5399677,...,18485.0,7623.0,20230.0,37865.0,28304.0,19706.0,24101.0,201908.0,42911.0,391612.0
1142,39020,제주특별자치도,서귀포시,2016,11,1845.997273,297.545455,22.363636,74,5885110,...,22075.0,8231.0,17817.0,43920.0,35152.0,25031.0,22788.0,209001.0,47846.0,423486.0
1143,39020,제주특별자치도,서귀포시,2017,11,1846.100909,280.636364,23.363636,64,6723287,...,23671.0,9871.0,17513.0,47349.0,37951.0,28645.0,25596.0,226649.0,46656.0,454634.0
1144,39020,제주특별자치도,서귀포시,2018,11,1853.310000,279.181818,24.363636,71,6844464,...,23306.0,9315.0,18132.0,50821.0,42747.0,27045.0,28828.0,245977.0,53187.0,487101.0

In [86]:
lib_dfs_sgg.to_excel('../data/3/result/sgg_lib.xlsx',index=False)

In [85]:
lib_ele_dfs.head()

,도서관명,시설_연면적,개관일수,AGE,직원_정규직,도서관총예산,도서_총류,도서_철학,도서_종교,도서_사회과학,...,대출권수_철학,대출권수_종교,대출권수_사회과학,대출권수_순수과학,대출권수_기술과학,대출권수_예술,대출권수_언어,대출권수_문학,대출권수_역사,대출권수
0,종로도서관,3553.00,320,95,26,1195309,14133,17707,9414,55515,...,21476.0,9895.0,9928.0,10113.0,30194.0,29405.0,10043.0,110861.0,23622.0,264927.0
1,정독도서관,13266.00,326,38,60,1688833,27524,22586,16546,105669,...,21833.0,9351.0,17783.0,20475.0,26201.0,41553.0,13926.0,130474.0,32511.0,313421.0
2,청운문학도서관,741.82,36,1,5,154458,128,30,29,94,...,1.0,0.0,7.0,23.0,5.0,2.0,0.0,3416.0,16.0,3470.0
3,아름꿈 도서관,467.95,233,1,3,303268,631,557,161,2038,...,234.0,146.0,854.0,1643.0,384.0,1271.0,190.0,3041.0,895.0,8813.0
4,서울시립어린이도서관,3796.63,326,36,26,714395,12555,6604,3972,39936,...,14231.0,9096.0,38998.0,97241.0,11966.0,8747.0,36756.0,277921.0,87503.0,568229.0

In [87]:
lib_ele_dfs.to_excel('../data/3/result/lib.xlsx',index=False)